---
- name: Setup AI tools on Jetson Nano
  hosts: localhost
  connection: local
  become: yes

  vars:

    system_timezone: Europe/London
    ntp_servers:
      - 0.arch.pool.ntp.org
      - 1.arch.pool.ntp.org
      - 2.arch.pool.ntp.org
      - 3.arch.pool.ntp.org
    ntp_fallback_servers:
      - 0.uk.pool.ntp.org
      - 0.pool.ntp.org
      - 1.pool.ntp.org
    ansible_user:
      - adehundeag
      - jwu


  tasks:


      # Configure NTP

    - name: Set time zone
      timezone:
        name: '{{ system_timezone }}'
      become: yes

    - name: Configure systemd-timesyncd
      template:
        src: timesyncd.conf.j2
        dest: /etc/systemd/timesyncd.conf
        owner: root
        group: root
        mode: 0644
      register: timesyncd_config
      become: yes

    - name: Restart systemd-timesyncd
      service:
        name: systemd-timesyncd
        enabled: yes
        state: restarted
      when: timesyncd_config.changed
      become: yes

    - name: Remove packages that are no longer required
      apt:
        autoremove: yes
      become: yes

      # Install  dependencies

    - name: Install essential packages
      apt:
        name:
          - python3-pip
          - git
          - build-essential
        state: present
    
    - name: Install pip packages
      pip:
      

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Add users to Docker group
      user:
        name: "{{ item }}"
        groups: docker
        append: yes
      loop: "{{ ansible_user }}"



    - name: Install NVIDIA Docker runtime
      shell: |
        distribution=$(. /etc/os-release;echo $ID$VERSION_ID)
        curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | sudo apt-key add -
        curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | sudo tee /etc/apt/sources.list.d/nvidia-docker.list
        sudo apt-get update
        sudo apt-get install -y nvidia-docker2
        sudo systemctl restart docker
      args:
        executable: /bin/bash

    - name : Installer curl
      apt:
        name: curl
        state: present

    - name: Installer json_pp (via perl)
      apt:
       name: libjson-pp-perl
       state: present
